set_property IOSTANDARD LVTTL [get_ports clk]
set_property PACKAGE_PIN N11 [get_ports clk]
# create_clock -period 50.000 -name clk -waveform {0.000 25.000} [get_ports clk]

set_property IOSTANDARD LVTTL [get_ports rst_n]
set_property PACKAGE_PIN T2 [get_ports rst_n]

set_property IOSTANDARD LVTTL [get_ports {i_start_matrix}]
set_property PACKAGE_PIN M2 [get_ports {i_start_matrix}]


set_property IOSTANDARD LVTTL [get_ports {o_start_matrix}]
set_property PACKAGE_PIN M1 [get_ports {o_start_matrix}]

# set_property IOSTANDARD LVTTL [get_ports {o_uart_tx}]
# set_property PACKAGE_PIN E3 [get_ports {o_uart_tx}]
# set_property IOSTANDARD LVTTL [get_ports {i_uart_rx}]
# set_property PACKAGE_PIN F5 [get_ports {i_uart_rx}]
set_property IOSTANDARD LVTTL [get_ports {i_uart_rx}]
set_property PACKAGE_PIN K13  [get_ports {i_uart_rx}]
set_property IOSTANDARD LVTTL [get_ports {o_uart_tx}]
set_property PACKAGE_PIN K12 [get_ports {o_uart_tx}]

set_property IOSTANDARD LVTTL [get_ports {o_bt_tx}]
set_property PACKAGE_PIN A5 [get_ports {o_bt_tx}]
set_property IOSTANDARD LVTTL [get_ports {i_bt_rx}]
set_property PACKAGE_PIN B4 [get_ports {i_bt_rx}]



# usb30

set_property IOSTANDARD LVTTL [get_ports {i_fx3_flaga}]
set_property PACKAGE_PIN N13 [get_ports {i_fx3_flaga}]
set_property IOSTANDARD LVTTL [get_ports {i_fx3_flagb}]
set_property PACKAGE_PIN T8 [get_ports {i_fx3_flagb}]
set_property IOSTANDARD LVTTL [get_ports {i_fx3_flagc}]
set_property PACKAGE_PIN P15 [get_ports {i_fx3_flagc}]
set_property IOSTANDARD LVTTL [get_ports {i_fx3_flagd}]
set_property PACKAGE_PIN M14 [get_ports {i_fx3_flagd}]

set_property IOSTANDARD LVTTL [get_ports {fx3_pclk}]
set_property PACKAGE_PIN N14 [get_ports {fx3_pclk}]

set_property IOSTANDARD LVTTL [get_ports {o_fx3_slcs_n}]
set_property PACKAGE_PIN N12 [get_ports {o_fx3_slcs_n}]
set_property IOSTANDARD LVTTL [get_ports {o_fx3_slwr_n}]
set_property PACKAGE_PIN M12 [get_ports {o_fx3_slwr_n}]
set_property IOSTANDARD LVTTL [get_ports {o_fx3_slrd_n}]
set_property PACKAGE_PIN P14 [get_ports {o_fx3_slrd_n}]
set_property IOSTANDARD LVTTL [get_ports {o_fx3_sloe_n}]
set_property PACKAGE_PIN P13 [get_ports {o_fx3_sloe_n}]
set_property IOSTANDARD LVTTL [get_ports {o_fx3_pktend_n}]
set_property PACKAGE_PIN P11 [get_ports {o_fx3_pktend_n}]
set_property IOSTANDARD LVTTL [get_ports {o_fx3_a[0]}]
set_property PACKAGE_PIN T9 [get_ports {o_fx3_a[0]}]
set_property IOSTANDARD LVTTL [get_ports {o_fx3_a[1]}]
set_property PACKAGE_PIN R10 [get_ports {o_fx3_a[1]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[0]}]
set_property PACKAGE_PIN L5 [get_ports {io_fx3_db[0]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[1]}]
set_property PACKAGE_PIN L4 [get_ports {io_fx3_db[1]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[2]}]
set_property PACKAGE_PIN M5 [get_ports {io_fx3_db[2]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[3]}]
set_property PACKAGE_PIN N4 [get_ports {io_fx3_db[3]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[4]}]
set_property PACKAGE_PIN P3 [get_ports {io_fx3_db[4]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[5]}]
set_property PACKAGE_PIN M4 [get_ports {io_fx3_db[5]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[6]}]
set_property PACKAGE_PIN M6 [get_ports {io_fx3_db[6]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[7]}]
set_property PACKAGE_PIN P4 [get_ports {io_fx3_db[7]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[8]}]
set_property PACKAGE_PIN P5 [get_ports {io_fx3_db[8]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[9]}]
set_property PACKAGE_PIN P6 [get_ports {io_fx3_db[9]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[10]}]
set_property PACKAGE_PIN N6 [get_ports {io_fx3_db[10]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[11]}]
set_property PACKAGE_PIN N9 [get_ports {io_fx3_db[11]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[12]}]
set_property PACKAGE_PIN P8 [get_ports {io_fx3_db[12]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[13]}]
set_property PACKAGE_PIN P10 [get_ports {io_fx3_db[13]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[14]}]
set_property PACKAGE_PIN P9 [get_ports {io_fx3_db[14]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[15]}]
set_property PACKAGE_PIN N3 [get_ports {io_fx3_db[15]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[16]}]
set_property PACKAGE_PIN R12 [get_ports {io_fx3_db[16]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[17]}]
set_property PACKAGE_PIN T10 [get_ports {io_fx3_db[17]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[18]}]
set_property PACKAGE_PIN T13 [get_ports {io_fx3_db[18]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[19]}]
set_property PACKAGE_PIN T14 [get_ports {io_fx3_db[19]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[20]}]
set_property PACKAGE_PIN R11 [get_ports {io_fx3_db[20]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[21]}]
set_property PACKAGE_PIN R13 [get_ports {io_fx3_db[21]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[22]}]
set_property PACKAGE_PIN T15 [get_ports {io_fx3_db[22]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[23]}]
set_property PACKAGE_PIN T12 [get_ports {io_fx3_db[23]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[24]}]
set_property PACKAGE_PIN N16 [get_ports {io_fx3_db[24]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[25]}]
set_property PACKAGE_PIN R16 [get_ports {io_fx3_db[25]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[26]}]
set_property PACKAGE_PIN R15 [get_ports {io_fx3_db[26]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[27]}]
set_property PACKAGE_PIN M15 [get_ports {io_fx3_db[27]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[28]}]
set_property PACKAGE_PIN P16 [get_ports {io_fx3_db[28]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[29]}]
set_property PACKAGE_PIN L13 [get_ports {io_fx3_db[29]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[30]}]
set_property PACKAGE_PIN L14 [get_ports {io_fx3_db[30]}]
set_property IOSTANDARD LVTTL [get_ports {io_fx3_db[31]}]
set_property PACKAGE_PIN M16 [get_ports {io_fx3_db[31]}]